name: Testing branch info

on: [push, pull_request]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  main_job:
    runs-on: ubuntu-latest  
    steps:
      - name: view the PR number
        run: |
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "PR number = ${{ env.PR_NUMBER }}"  
