name: Testing branch info

on: 
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_NUMBER_URL: https://he-members-staging-pr-${{ github.event.pull_request.number }}.herokuapp.com

jobs:
  main_job:
    runs-on: ubuntu-latest  
    steps:
      - name: view the PR number
        run: |
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "URL = ${{ env.PR_NUMBER_URL }}"  
