name: Testing branch info

on: [push, pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
        
      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"
        
      - name: Echo the GITHUB_REF
        run: echo "Branch name ${GITHUB_REF}"GITHUB_EVENT_PATH
        
      - name: Echo the GITHUB_EVENT_PATH
        run: echo "Branch name ${GITHUB_EVENT_PATH}"        
